# -*- coding: utf-8 -*-
"""
Created on Tue May 20 17:08:11 2025

@author: llemarchand
"""

import math
from .VHDL_types import SFixed
from . import operation_vhdl as op

class HillMuscle:
    def __init__(
        self,
        L: float,
        B: float,
        Kpe: float,
        Kse: float,
        max_active_tension: float,
        steepness: float,
        x_offset: float,
        y_offset: float,
        L_rest: float,
        L_width: float,
        nb_bits_integer,
        nb_bits_decimal
    ):
        """

        Parameters
        ----------
        L : float
            muscle length m
        B : float
            damping coefficient (viscosity) Ns/m
        Kpe : float
            stiffness of the parallel elastic element N/m
        Kse : float
            stiffness of the serie elastic element N/m
        Max_active_tension : float
            maximal active tension N
        amp : float
            to set the shape of the tension stimulus curve
        steepness : float
            to set the shape of the tension stimulus curve
        x_offset : float
            to set the shape of the tension stimulus curve
        y_offset : float
            to set the shape of the tension stimulus curve
        L_rest : float
            rest/optimal length of the muscle m, set the shape of length tension curve m
        L_width : float
            set the shape of length tension curve m
        T : float
            Muscle force output

        """
        self.L = SFixed(L, nb_bits_integer, nb_bits_decimal)
        """Muscle length in L0?"""
        self.B = SFixed(B, nb_bits_integer, nb_bits_decimal)
        self.Kpe = SFixed(Kpe, nb_bits_integer, nb_bits_decimal)
        self.Kse = SFixed(Kse, nb_bits_integer, nb_bits_decimal)
        self.max_active_tension = SFixed(max_active_tension, nb_bits_integer, nb_bits_decimal)
        self.steepness = SFixed(steepness, nb_bits_integer, nb_bits_decimal)
        self.x_offset = SFixed(x_offset, nb_bits_integer, nb_bits_decimal)
        self.y_offset = SFixed(y_offset, nb_bits_integer, nb_bits_decimal)
        self.L_rest = SFixed(L_rest, nb_bits_integer, nb_bits_decimal)
        self.L_width = SFixed(L_width, nb_bits_integer, nb_bits_decimal)
        self.T = SFixed(0, nb_bits_integer, nb_bits_decimal)
        self.A = SFixed(0, nb_bits_integer, nb_bits_decimal)
        self.nb_bits_integer = nb_bits_integer
        self.nb_bits_decimal = nb_bits_decimal 


        ##### pour debug ####
        self.first_term = SFixed(0, self.nb_bits_integer, self.nb_bits_decimal)
        self.damping_contribution = SFixed(0, self.nb_bits_integer, self.nb_bits_decimal)
        self.second_term = SFixed(0, self.nb_bits_integer, self.nb_bits_decimal)




    def stimulus_tension(self, V):      ###################### ON TESTE DES TRUCS ###################  APPROXIMATION LINAIRE PAR FONCTION AFFINES 
        """
            Parameters
            ----------
            V : float
                entering stimulus in the force generator

            Returns
            -------
            A : float
                active tension generated by the force generator
        1)formule Animatlab
        """
    
        if V.float_value <= -60:
            A = op.add(
            op.mul(SFixed(0, self.nb_bits_integer, self.nb_bits_decimal), V),
            SFixed(0, self.nb_bits_integer, self.nb_bits_decimal))
        

        elif (V.float_value <= 0) & (V.float_value > -60):
            A = op.add(
                op.mul(SFixed(6.5, self.nb_bits_integer, self.nb_bits_decimal), V),
                SFixed(390, self.nb_bits_integer, self.nb_bits_decimal)
            )

        elif (V.float_value >= 0):
            A = op.add(
                op.mul(SFixed(0, self.nb_bits_integer, self.nb_bits_decimal), V),
                SFixed(390, self.nb_bits_integer, self.nb_bits_decimal)
            )

        
        A_final_float = max(0, min(A.float_value, 400))
        self.A = SFixed(A_final_float, self.nb_bits_integer, self.nb_bits_decimal)
        return self.A


    def length_tension(self,L):
        """

            Returns
            -------
            Percentage_tension_used : float
                percentage of the tension usable which depends on the actual muscle length
        1)formule Animatlab

        """
        delta_L = op.sub(L, self.L_rest)                    ##      Percentage_tension_used: float = 1 - (
                                                        ##          (self.L - self.L_rest) ** 2 / (self.L_width) ** 2
        Percentage_tension_used = op.sub(SFixed(1,self.nb_bits_integer, self.nb_bits_decimal),op.div(op.mul(delta_L,delta_L), op.mul(self.L_width,self.L_width)))                                    ##      )
                                         ##      return Percentage_tension_used
        return Percentage_tension_used
    

    def update(self, V, dt, L, dL):
        """


            Parameters
            ----------
            V : float
                entering stimulus in the force generator
            dt : float
                time step ms
            dL : float
                muscle length change m

            Returns
            -------
            T : float
                muscle force N
        1)calculate new muscle length
        2)calculate active force
        3)calculate new muscle force
        4)apply length tension relationship to get the new appliable muscle force in the mechanical model

        """

        self.L = SFixed(L,self.nb_bits_integer, self.nb_bits_decimal)   
        self.dL= SFixed(dL, self.nb_bits_integer, self.nb_bits_decimal)
        self.A = self.stimulus_tension(V)                                          ####self.stimulus_tension(V)
        self.A = op.mul(self.A, self.length_tension(self.L))     
         
        self.first_term = op.div(self.Kse, self.B)                                                                                       ####self.A *= self.length_tension()
        self.damping_contribution = op.mul(self.B,self.dL)                                                                                  ####self.T += (
        self.second_term = op.mul(self.T,op.add(SFixed(1,self.nb_bits_integer, self.nb_bits_decimal),op.div(self.Kpe, self.Kse)))                                                            ####    self.Kse
                                                                                                                                                     ####    / (self.B)
                                                                                                                                         ####    * (
        self.dT = op.mul(op.sub(op.add(self.damping_contribution,self.A), self.second_term), self.first_term)                                                            ####        #                self.Kpe * (self.L - self.L_rest) # a retirer pcq lrest toujours superieur à L et donc pas de force?
                                                                                                                                ####        +self.B * (dL) - (1 + (self.Kpe / self.Kse)) * self.T + self.A
                                                                                                                                              ####    )
        self.T = op.euler_integration(self.T, self.dT, dt)                                                                           ####) * (dt)
                                                                                                                                        ####if self.T < 0:
        if self.T.float_value < 0:
            self.T = SFixed(0, self.nb_bits_integer, self.nb_bits_decimal)                                                            ####    self.T = 0
                                                                    ####                                                           ####return self.T
