# -*- coding: utf-8 -*-
"""
Created on Tue May 20 17:08:11 2025

@author: llemarchand
"""

import math


class HillMuscle:
    def __init__(
        self,
        L: float,
        B: float,
        Kpe: float,
        Kse: float,
        max_active_tension: float,
        steepness: float,
        x_offset: float,
        y_offset: float,
        L_rest: float,
        L_width: float,
    ):
        """

        Parameters
        ----------
        L : float
            muscle length m
        B : float
            damping coefficient (viscosity) Ns/m
        Kpe : float
            stiffness of the parallel elastic element N/m
        Kse : float
            stiffness of the serie elastic element N/m
        Max_active_tension : float
            maximal active tension N
        amp : float
            to set the shape of the tension stimulus curve
        steepness : float
            to set the shape of the tension stimulus curve
        x_offset : float
            to set the shape of the tension stimulus curve
        y_offset : float
            to set the shape of the tension stimulus curve
        L_rest : float
            rest/optimal length of the muscle m, set the shape of length tension curve m
        L_width : float
            set the shape of length tension curve m
        T : float
            Muscle force output

        """
        self.L = L
        self.B = B
        self.Kpe = Kpe
        self.Kse = Kse
        self.max_active_tension = max_active_tension
        self.steepness = steepness
        self.x_offset = x_offset
        self.y_offset = y_offset
        self.L_rest = L_rest
        self.L_width = L_width
        self.T = 0
        self.A = 0

    def stimulus_tension(self, V: float):
        """
            Parameters
            ----------
            V : float
                entering stimulus in the force generator

            Returns
            -------
            A : float
                active tension generated by the force generator
        1)formule Animatlab
        """
        self.A = (
            self.max_active_tension
            / (1 + math.exp((self.steepness) * (self.x_offset - V / 1000)))
            + self.y_offset
        )

        self.A = max(0, min(self.A, 400))


    def length_tension(self):
        """

            Returns
            -------
            Percentage_tension_used : float
                percentage of the tension usable which depends on the actual muscle length
        1)formule Animatlab

        """
        Percentage_tension_used: float = 1 - (
            (self.L - self.L_rest) ** 2 / (self.L_width) ** 2
        )
        return Percentage_tension_used

    def update(self, V: float, dt: float, L: float, dL: float):
        """


            Parameters
            ----------
            V : float
                entering stimulus in the force generator
            dt : float
                time step ms
            dL : float
                muscle length change m

            Returns
            -------
            T : float
                muscle force N
        
        1) calculate active tension depending on the level of depalorization of alpha motoneuron
        2) calcule the percentage of tension that is gonna be used depending on the muscle length
        3) apply this active force in the hill muscle model, see shadmher and wise for equations

        """
        self.L = L
        self.stimulus_tension(V)
        self.A *= self.length_tension()
        self.T += (
            self.Kse
            / (self.B)
            * (
                #                self.Kpe * (self.L - self.L_rest) # a retirer pcq lrest toujours superieur à L et donc pas de force?
                +self.B * (dL) - (1 + (self.Kpe / self.Kse)) * self.T + self.A
            )
        ) * (dt)
        if self.T < 0:
            self.T = 0

        return self.T
